### ISSUE TITLE
Téléchargement des GTF

### ISSUE THREAD

**Issue by liatia** [CharlesJB/anno#4]
Ajouter une option pour le téléchargement des GTF.

Trouver le bon lien pour chaque organismes sur: http://useast.ensembl.org/info/data/ftp/index.html/

Télécharger le fichier avec le bon nom, voir par exemple: https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L115-L116

**Comment by EmeTexe** [comment]
- [x] Ajouter le paramètre download gtf
- [x] Créer une fonction pour télécharger le gtf
- [x] mettre à jour la documentation

**Comment by EmeTexe** [comment]
- [x] Ajouter le md5sum du gtf
