### ISSUE TITLE
Nouvelle version Rattus norvegicus

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/anno#6]
Le code ne fonctionne plus avec Rattus norvegicus car il y a une nouvelle version.

Dans le code présentement, il utilise Rnor_6.0: https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L251

Sur Ensembl, c'est maintenant mRatBN7.2: http://ftp.ensembl.org/pub/release-108/fasta/rattus_norvegicus/cdna/

Il faut:

- [x] Trouver la release à partir de laquelle le changement a eu lieu
- [x] Modifier le code de manière similaire à ce qu'on avait fait précédemment pour Mus musculus (https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L230-L244)
- [x] Ne pas oublier de mettre à jour la version dans le fichier DESCRIPTION

**Comment by EmeTexe** [comment]
Le nom du génome de Rattus norvegicus est passé de `Rattus_norvegicus.Rnor_6.0.cdna.all.fa.gz`, pour les versions d'ensembl 104 et moins, à `Rattus_norvegicus.mRatBN7.2.cdna.all.fa.gz` pour les versions suivantes. Un problème qui est apparu est le changement du prefix des chromosomes, passant de `chromosome` à `primary_assembly`. Problème réglé en [ligne 153](https://github.com/CharlesJB/anno/blob/master/R/prepare_anno.R#L153).
