### ISSUE TITLE
Ajouter un paramètre path

### ISSUE THREAD

**Issue by EmeTexe** [CharlesJB/anno#7]
Pour le moment les sorties sont sauvegardées dans le répertoire courant, a terme il peut être intéressant de créer un argument path permettant de sauvegarder les sorties dans un dossier au choix. le défaut de ce path restera ".", le dossier courant.

A faire : 

- [x] Ajouter un argument path, defaut "."
- [x] Ajouter ce path au prefix lors de la sauvegarde des fichiers
- [x] Tester l'ajout du path
- [x] Mettre à jour le manuel de la fonction

**Comment by CharlesJB** [comment]
Pour mieux correspondre avec les conventions d'autres paquets sur lesquels j'ai travaillé, il serait mieux d'utiliser le nom `outdir` au lieu de `path`. Je crois aussi que ce terme est plus précis pour décrire le rôle de ce paramètre.

**Comment by CharlesJB** [comment]
Il faudrait également mettre à jour la documentation en faisant un `devtools::document()`.  Ça va automatiquement mettre le bon fichier à jour dans le dossier `man/`.

**Comment by EmeTexe** [comment]
fait ici 4b14ffd8c95ba1477ac3546fd7147618a1bade9f
